### ISSUE TITLE
Update to Focal (20.04)? 

### ISSUE THREAD

**Issue by RobinCPC** [solarkennedy/wine-x11-novnc-docker#16]
It seams that Eoan reach end-of-life. Here is the message I got when I use 'apt-get update'
![圖片](https://user-images.githubusercontent.com/5998887/103555283-f97d8a00-4eea-11eb-9b8e-371b133175b9.png)

I have modified your Dockerfile to use Focal (20.04) as based image in my fork. Here is the links:
https://github.com/RobinCPC/wine-x11-novnc-docker
https://hub.docker.com/repository/docker/robincpc/wine-x11-novnc-docker

If you think it is OK, I would like to make a pull request.  

P.S. Your docker image is awesome. I use your image to run our company's robot simulation (Windows-based).

**Comment by solarkennedy** [comment]
Yes please! PR.

**Comment by solarkennedy** [comment]
Closed via #17
