### ISSUE TITLE
No network access

### ISSUE THREAD

**Issue by pmjohann** [solarkennedy/wine-x11-novnc-docker#7]
First of all, thank you for this great image, exactly what and how I wanted to build it myself!

I have one major problem though, .exe executed with wine seem unable to make any kind of network connections, such as:
- I can not ping any host (not even localhost)
- Database manager can not connect to any DB instance
- Web browsers (built in iexplore.exe and also tried Google Chrome) can't access any host either.

I did 2 hours of research, ping seems to be a separate issue, but no network access does not seem to be normal.

Any suggestions? Thanks!

**Comment by solarkennedy** [comment]
Hard to say. Try running `docker run --net=host` ?

**Comment by pmjohann** [comment]
I’ll try it tomorrow and report back, thanks.

**Comment by pmjohann** [comment]
This issue is resolved with current version, thank you, keep up the good work!
